version: '3.9'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: mydatabase
    profiles:
      - dev
      - prod

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    profiles:
      - dev
      - prod

volumes:
  mongo_data:
  redis_data:

networks:
  default:
    external: true
    name: app-shared