name: Validate Docker Compose (Infra)

on:
  push:
    paths:
      - '**/docker-compose.yml'
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate docker-compose.yml
        run: docker compose -f docker-compose.yml config